export default {
  REQUESTED_REPOS: 'REQUESTED_REPOS',
  REQUESTED_REPOS_ASYNC: 'REQUESTED_REPOS_ASYNC',
  REQUESTED_REPOS_SUCCESS: 'REQUESTED_REPOS_SUCCESS',
  REQUESTED_REPOS_ERROR: 'REQUESTED_REPOS_ERROR',
  FOCUSED_SEARCH_INPUT: 'FOCUSED_SEARCH_INPUT',
  UNFOCUSED_SEARCH_INPUT: 'UNFOCUSED_SEARCH_INPUT',
};
